/** Data Loom workspace: client-side navigation and state are intentionally isolated so Phase 2 APIs can replace the mock layer. */
"use client";
import { useEffect, useState } from "react";
import { Boxes, FileOutput, History, Menu, Moon, Sun, TableProperties, X } from "lucide-react";
import { ProductMark } from "@/components/layout/product-mark";
import { ExtractionForm } from "@/components/extraction/extraction-form";
import { OperationThread } from "@/components/operation/operation-thread";
import { ResultWorkspace } from "@/components/results/result-workspace";
import { RunsLedger } from "@/components/runs/runs-ledger";
import { useJobWorkspace } from "@/hooks/use-job-workspace";
import type { ExtractionRequest } from "@/types/extraction";
type View = "workspace" | "runs" | "datasets" | "exports";
const navigation: { id: View; label: string; icon: typeof Boxes }[] = [{ id: "workspace", label: "Workspace", icon: Boxes }, { id: "runs", label: "Runs", icon: History }, { id: "datasets", label: "Datasets", icon: TableProperties }, { id: "exports", label: "Exports", icon: FileOutput }];
export default function Page() { const [theme, setTheme] = useState<"light" | "dark">("light"); const [view, setView] = useState<View>("workspace"); const [menuOpen, setMenuOpen] = useState(false); const { run, start, progress, job, files, results, resultsLoading, resultsError, selectResultsPage, cancel } = useJobWorkspace(); useEffect(() => { if (new URLSearchParams(window.location.search).get("theme") === "dark") setTheme("dark"); }, []); const begin = (request: ExtractionRequest) => { void start(request); setView("workspace"); }; return <div className="app" data-theme={theme}><header className="product-header"><div className="header-inner"><ProductMark /><nav className={menuOpen ? "nav-open" : ""} aria-label="Primary navigation">{navigation.map((item) => { const Icon = item.icon; return <button key={item.id} type="button" className={view === item.id ? "active" : ""} onClick={() => { setView(item.id); setMenuOpen(false); }}><Icon size={16} />{item.label}</button>; })}</nav><div className="header-actions"><button className="theme-toggle" type="button" onClick={() => setTheme((current) => current === "light" ? "dark" : "light")} aria-label={`Switch to ${theme === "light" ? "dark" : "light"} mode`}>{theme === "light" ? <Moon size={17} /> : <Sun size={17} />}</button><button className="menu-toggle" type="button" onClick={() => setMenuOpen((current) => !current)} aria-expanded={menuOpen} aria-label="Toggle navigation">{menuOpen ? <X size={19} /> : <Menu size={19} />}</button></div></div></header><main>{job && !["COMPLETED", "FAILED", "CANCELLED", "READY_FOR_EXPORT"].includes(job.status) && <button type="button" className="cancel-job" onClick={() => void cancel()}>Cancel job</button>}{view === "workspace" ? <><div className="workspace-shell"><ExtractionForm onStart={begin} isRunning={run?.state === "running"} /><OperationThread run={run} progress={progress} /></div>{run?.state === "completed" && <><ResultWorkspace run={run} results={results} loading={resultsLoading} error={resultsError} onPageChange={selectResultsPage} /><section className="export-files" aria-labelledby="export-files-title"><p className="overline">Generated artifacts</p><h2 id="export-files-title">Validated exports</h2>{files.length ? <ul>{files.map((file) => <li key={file.file_id}><span>{file.format.toUpperCase()} · {file.filename} · {file.byte_size.toLocaleString()} bytes</span>{file.download_url && <a href={file.download_url}>Download</a>}</li>)}</ul> : <p>Exports are not available yet.</p>}</section></>}</> : <RunsLedger run={run} view={view} />}</main><footer className="product-footer"><span>Live backend workspace</span><span>{job ? `Job ${job.status.replaceAll("_", " ")}` : "Create a run to begin"}</span></footer></div>; }
