/** Data Loom workspace: client-side navigation and state are intentionally isolated so Phase 2 APIs can replace the mock layer. */
"use client";
import { useEffect, useState } from "react";
import { Boxes, FileOutput, History, Menu, Moon, Sun, TableProperties, X } from "lucide-react";
import { ProductMark } from "@/components/layout/product-mark";
import { ExtractionForm } from "@/components/extraction/extraction-form";
import { OperationThread } from "@/components/operation/operation-thread";
import { ResultWorkspace } from "@/components/results/result-workspace";
import { RunsLedger } from "@/components/runs/runs-ledger";
import { useMockExtraction } from "@/hooks/use-mock-extraction";
import type { ExtractionRequest } from "@/types/extraction";
type View = "workspace" | "runs" | "datasets" | "exports";
const navigation: { id: View; label: string; icon: typeof Boxes }[] = [{ id: "workspace", label: "Workspace", icon: Boxes }, { id: "runs", label: "Runs", icon: History }, { id: "datasets", label: "Datasets", icon: TableProperties }, { id: "exports", label: "Exports", icon: FileOutput }];
export default function Page() { const [theme, setTheme] = useState<"light" | "dark">("light"); const [view, setView] = useState<View>("workspace"); const [menuOpen, setMenuOpen] = useState(false); const { run, start, progress } = useMockExtraction(); useEffect(() => { if (new URLSearchParams(window.location.search).get("theme") === "dark") setTheme("dark"); }, []); const begin = (request: ExtractionRequest) => { start(request); setView("workspace"); }; return <div className="app" data-theme={theme}><header className="product-header"><div className="header-inner"><ProductMark /><nav className={menuOpen ? "nav-open" : ""} aria-label="Primary navigation">{navigation.map((item) => { const Icon = item.icon; return <button key={item.id} type="button" className={view === item.id ? "active" : ""} onClick={() => { setView(item.id); setMenuOpen(false); }}><Icon size={16} />{item.label}</button>; })}</nav><div className="header-actions"><button className="theme-toggle" type="button" onClick={() => setTheme((current) => current === "light" ? "dark" : "light")} aria-label={`Switch to ${theme === "light" ? "dark" : "light"} mode`}>{theme === "light" ? <Moon size={17} /> : <Sun size={17} />}</button><button className="menu-toggle" type="button" onClick={() => setMenuOpen((current) => !current)} aria-expanded={menuOpen} aria-label="Toggle navigation">{menuOpen ? <X size={19} /> : <Menu size={19} />}</button></div></div></header><main>{view === "workspace" ? <><div className="workspace-shell"><ExtractionForm onStart={begin} isRunning={run?.state === "running"} /><OperationThread run={run} progress={progress} /></div>{run?.state === "completed" && <ResultWorkspace run={run} />}</> : <RunsLedger run={run} view={view} />}</main><footer className="product-footer"><span>Phase 1 client prototype</span><span>Mock lifecycle aligned to the documented job model</span></footer></div>; }
