/** Data Loom Phase 9: maps real job status and SSE milestones into the existing visual system. */
"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { jobsApi, type JobStatusResponse } from "@/lib/api-client";
import type { ExtractionRequest, MockRun, RunEvent } from "@/types/extraction";
const stageMap: Record<string, RunEvent["stage"]> = { PLANNING: "planning", DISCOVERING: "discovery", EXTRACTING: "extraction", VALIDATING: "validation", READY_FOR_EXPORT: "export", EXPORTING: "export" };
const mapStage = (status: string): RunEvent["stage"] => stageMap[status] ?? "source";
const mapRun = (job: JobStatusResponse, formats: MockRun["outputFormats"] = []): MockRun => ({ id: job.job_id, sourceUrl: "Connected source", outputFormats: formats, state: job.status === "COMPLETED" || job.status === "READY_FOR_EXPORT" ? "completed" : job.status === "FAILED" ? "failed" : "running", startedAt: job.created_at, events: [{ stage: mapStage(job.status), status: job.status === "FAILED" ? "failed" : job.status === "COMPLETED" || job.status === "READY_FOR_EXPORT" ? "completed" : "active", message: job.error?.message ?? `Current stage: ${job.status.replaceAll("_", " ")}` }] });
export function useJobWorkspace() { const [job, setJob] = useState<JobStatusResponse | null>(null); const [run, setRun] = useState<MockRun | null>(null); const [error, setError] = useState<string | null>(null); const refresh = useCallback(async (id: string) => { const next = await jobsApi.status(id); setJob(next); setRun(mapRun(next)); return next; }, []); const start = useCallback(async (request: ExtractionRequest) => { setError(null); const created = await jobsApi.create({ project_id: "00000000-0000-0000-0000-000000000000", source_url: request.sourceUrl, task: request.intent, fields: [], output_formats: request.outputFormats.filter((format) => ["xlsx", "csv", "json"].includes(format)), options: { max_pages: request.maxPages, max_records: request.maxRecords, follow_pagination: request.followPagination, follow_relevant_links: request.followLinks, extract_images: false, deduplicate: request.removeDuplicates, validate: request.validateResults } }, crypto.randomUUID()); await refresh(created.job_id); window.history.replaceState(null, "", `?job=${created.job_id}`); }, [refresh]); useEffect(() => { const id = new URLSearchParams(window.location.search).get("job"); if (id) void refresh(id); }, [refresh]); useEffect(() => { if (!job || ["COMPLETED", "FAILED", "CANCELLED"].includes(job.status)) return; const stream = new EventSource(jobsApi.eventsUrl(job.job_id)); stream.onmessage = () => void refresh(job.job_id); stream.onerror = () => { stream.close(); window.setTimeout(() => void refresh(job.job_id), 1500); }; return () => stream.close(); }, [job, refresh]); const progress = useMemo(() => job?.progress.progress_percent ?? 0, [job]); return { run, progress, job, error, start, cancel: async () => job && refresh((await jobsApi.cancel(job.job_id)).job_id) }; }
