"""phase 2 durable job foundation

Revision ID: 0001_phase2_job_foundation
Revises:
Create Date: 2026-08-22
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_phase2_job_foundation"
down_revision = None
branch_labels = None
depends_on = None

job_status = "status IN ('QUEUED','PLANNING','BROWSER_INITIALIZING','DISCOVERING','EXTRACTING','VALIDATING','EXPORTING','COMPLETED','FAILED','CANCELLED')"


def timestamps(columns: list[sa.Column]) -> list[sa.Column]:
    return columns + [sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"))]


def upgrade() -> None:
    op.create_table("users", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("status", sa.String(32), nullable=False, server_default="ACTIVE"), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"))]), sa.CheckConstraint("status IN ('ACTIVE','SUSPENDED','DELETED')", name="ck_users_status"))
    op.create_index("ix_users_status", "users", ["status"])
    op.create_table("projects", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("owner_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False), sa.Column("name", sa.String(200), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="ACTIVE"), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"))]), sa.CheckConstraint("status IN ('ACTIVE','ARCHIVED')", name="ck_projects_status"))
    op.create_index("ix_projects_owner_updated", "projects", ["owner_id", "updated_at"])
    op.create_table("sources", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("canonical_url", sa.Text(), nullable=False), sa.Column("domain", sa.String(253), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"))]), sa.UniqueConstraint("project_id", "canonical_url", name="uq_sources_project_canonical_url"))
    op.create_index("ix_sources_project_domain", "sources", ["project_id", "domain"])
    op.create_table("extraction_jobs", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="RESTRICT"), nullable=False), sa.Column("source_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("sources.id", ondelete="RESTRICT"), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="QUEUED"), sa.Column("status_version", sa.Integer(), nullable=False, server_default="0"), sa.Column("task_description", sa.Text(), nullable=False), sa.Column("requested_fields", postgresql.JSONB(), nullable=False, server_default="[]"), sa.Column("options", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("output_formats", postgresql.JSONB(), nullable=False, server_default="[]"), sa.Column("progress_percent", sa.Integer(), nullable=False, server_default="0"), sa.Column("pages_discovered", sa.Integer(), nullable=False, server_default="0"), sa.Column("pages_processed", sa.Integer(), nullable=False, server_default="0"), sa.Column("records_found", sa.Integer(), nullable=False, server_default="0"), sa.Column("records_valid", sa.Integer(), nullable=False, server_default="0"), sa.Column("last_error_code", sa.String(80)), sa.Column("last_error_message", sa.String(500)), sa.Column("retryable", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("attempt", sa.Integer(), nullable=False, server_default="0"), sa.Column("max_attempts", sa.Integer(), nullable=False, server_default="3"), sa.Column("cancel_requested_at", sa.DateTime(timezone=True)), sa.Column("cancelled_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id")), sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("lease_owner", sa.String(200)), sa.Column("lease_expires_at", sa.DateTime(timezone=True)), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"))]), sa.CheckConstraint(job_status, name="ck_extraction_jobs_status"), sa.CheckConstraint("progress_percent >= 0 AND progress_percent <= 100", name="ck_jobs_progress_percent"))
    op.create_index("ix_jobs_project_created", "extraction_jobs", ["project_id", "created_at"])
    op.create_index("ix_jobs_status_created", "extraction_jobs", ["status", "created_at"])
    op.create_table("extraction_plans", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("extraction_jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("plan", postgresql.JSONB(), nullable=False), sa.Column("model_name", sa.String(200)), sa.Column("status", sa.String(32), nullable=False, server_default="DRAFT")]), sa.UniqueConstraint("job_id", "version", name="uq_plans_job_version"), sa.CheckConstraint("status IN ('DRAFT','ACTIVE','REJECTED')", name="ck_plans_status"))
    op.create_index("ix_plans_job_created", "extraction_plans", ["job_id", "created_at"])
    op.create_table("pages", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("extraction_jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("url", sa.Text(), nullable=False), sa.Column("canonical_url", sa.Text(), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="DISCOVERED"), sa.Column("snapshot_key", sa.String(512)), sa.Column("content_hash", sa.String(128)), sa.Column("discovered_at", sa.DateTime(timezone=True)), sa.Column("captured_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("job_id", "canonical_url", name="uq_pages_job_canonical_url"))
    op.create_index("ix_pages_job_status", "pages", ["job_id", "status"])
    op.create_index("ix_pages_content_hash", "pages", ["content_hash"])
    op.create_table("records", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("extraction_jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("page_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("pages.id", ondelete="SET NULL")), sa.Column("payload", postgresql.JSONB(), nullable=False), sa.Column("content_hash", sa.String(128)), sa.Column("confidence", sa.Float())]))
    op.create_index("ix_records_job_created", "records", ["job_id", "created_at"])
    op.create_index("ix_records_content_hash", "records", ["content_hash"])
    op.create_table("validation_results", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("extraction_jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("record_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("records.id", ondelete="SET NULL")), sa.Column("status", sa.String(32), nullable=False, server_default="PENDING"), sa.Column("findings", postgresql.JSONB(), nullable=False, server_default="{}")]))
    op.create_index("ix_validation_job_status", "validation_results", ["job_id", "status"])
    op.create_table("export_jobs", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("extraction_jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("format", sa.String(20), nullable=False), sa.Column("request_key", sa.String(100), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="QUEUED"), sa.Column("error_code", sa.String(80)), sa.Column("completed_at", sa.DateTime(timezone=True))]), sa.UniqueConstraint("job_id", "format", "request_key", name="uq_exports_job_format_key"))
    op.create_index("ix_exports_job_status", "export_jobs", ["job_id", "status"])
    op.create_table("generated_files", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("export_job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("export_jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("storage_key", sa.String(512), nullable=False), sa.Column("media_type", sa.String(200), nullable=False), sa.Column("byte_size", sa.BigInteger(), nullable=False), sa.Column("checksum", sa.String(128), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True))]), sa.UniqueConstraint("storage_key", name="uq_generated_files_storage_key"))
    op.create_index("ix_files_expiry", "generated_files", ["expires_at"])
    op.create_table("progress_events", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("extraction_jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("sequence_no", sa.BigInteger(), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("payload", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("correlation_id", postgresql.UUID(as_uuid=True), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP"))]), sa.UniqueConstraint("job_id", "sequence_no", name="uq_events_job_sequence"))
    op.create_index("ix_events_job_occurred", "progress_events", ["job_id", "occurred_at"])
    op.create_index("ix_events_job_type", "progress_events", ["job_id", "event_type"])
    op.create_table("idempotency_keys", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("key", sa.String(255), nullable=False), sa.Column("request_hash", sa.String(128), nullable=False), sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("extraction_jobs.id", ondelete="CASCADE"), nullable=False)]), sa.UniqueConstraint("project_id", "key", name="uq_idempotency_project_key"))
    op.create_table("work_outbox", *timestamps([sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("job_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("extraction_jobs.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("command_type", sa.String(80), nullable=False), sa.Column("operation_key", sa.String(100), nullable=False), sa.Column("payload", postgresql.JSONB(), nullable=False), sa.Column("attempt", sa.Integer(), nullable=False, server_default="1"), sa.Column("available_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")), sa.Column("published_at", sa.DateTime(timezone=True))]), sa.UniqueConstraint("operation_key", name="uq_outbox_operation_key"))
    op.create_index("ix_outbox_pending", "work_outbox", ["published_at", "available_at"])


def downgrade() -> None:
    for table in ["work_outbox", "idempotency_keys", "progress_events", "generated_files", "export_jobs", "validation_results", "records", "pages", "extraction_plans", "extraction_jobs", "sources", "projects", "users"]:
        op.drop_table(table)
